# add employee

# --- !Ups

use `crud`

DROP TABLE if exists EMPLOYEE_DETAIL;
DROP TABLE if exists EMPLOYEE;

CREATE TABLE `formdemo`.`EMPLOYEE` (
    `EMPLOYEE_ID` INT NOT NULL AUTO_INCREMENT,
    `EMAIL` VARCHAR(45) NOT NULL,
    `PASSWORD` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`EMPLOYEE_ID`)
) ENGINE=InnoDB;


CREATE TABLE `formdemo`.`EMPLOYEE_DETAIL` (
    `EMPLOYEE_DETAIL_ID` INT NOT NULL AUTO_INCREMENT,
    `EMPLOYEE_ID` INT NOT NULL,
    `NAME` VARCHAR(45) NOT NULL,
    `DESIGNATION` VARCHAR(45) NOT NULL,
    `ADDRESS` VARCHAR(100) NOT NULL,
    `CONTACT_NO` VARCHAR(20) NOT NULL,
    PRIMARY KEY (`EMPLOYEE_DETAIL_ID`),

    INDEX `fk_EMPLOYEE_ID_idx` (`EMPLOYEE_ID` ASC),

    CONSTRAINT `fk_EMPLOYEE_ID`
        FOREIGN KEY (`EMPLOYEE_ID`)
        REFERENCES `formdemo`.`EMPLOYEE` (`EMPLOYEE_ID`)
) ENGINE=InnoDB;




# --- !Downs

use `crud`

DROP TABLE if exists EMPLOYEE_DETAIL;
DROP TABLE if exists EMPLOYEE;


